apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rap8c6xka-java-quarkus
  janus-idp.io/tekton: rap8c6xka-java-quarkus
  backstage.io/kubernetes-id: rap8c6xka-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rap8c6xka-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
